name: Makefile CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          add-to-path: false

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25

      - name: Install dependencies
        run: sudo apt install libasound2-dev

      - name: Build
        run: make release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./release/mifasol*
          draft: true
